name: "Test CLI Environment"
# Checks that the package is usable as CLI tool.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
      - "Commit Message Title Validation"
      - "Coverage"
      - "Formatting"
      - "Linting"
      - "Prevent ByteOrderMarks"
      - "Test Dev Environment"
      - "Unittests"
    types: [completed]

jobs:
  # this dummy job is only added in order for this workflow to be listed in the pull request checks
  wait-for-other-workflows:
    name: Wait until other workflows have finished
    runs-on: ubuntu-latest
    steps:
      - name: Log Start of Workflow
        run: echo "Workflow triggered for visibility in pull request checks."

  check:
    name: Run CLI Test
    # abort if above-mentioned workflows fail
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Try to install the script, then run the CLI
        run: |
          pip install .
          ahlbatross
